### ISSUE TITLE
Integration fails to load d/t dependency issue

### ISSUE THREAD

**Issue by bovender** [Xyaren/homeassistant-magentatv#35]
## System Information

version | core-2023.8.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.32.1
Stage | running
Available Repositories | 1267
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.4
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 234.7 GB
disk_used | 7.8 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | failed to load: timeout
installed_addons | Let's Encrypt (4.12.9), VLC (0.2.0), Git pull (7.13.1), Studio Code Server (5.10.1), Nginx Proxy Manager (0.12.3), MariaDB (2.6.1), Advanced SSH & Web Terminal (15.0.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13. August 2023 um 06:47
-- | --
current_recorder_run | 18. August 2023 um 11:26
estimated_db_size | 408.20 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/Xyaren/homeassistant-magentatv/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The magentatv integration fails with recent versions of HA.

Log:

```
Setup failed for custom integration magentatv: Requirements for magentatv not found: ['async-upnp-client==0.33.2']
Unable to install package async-upnp-client==0.33.2: ERROR: Cannot install async-upnp-client==0.33.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip
````

It used to work before. I think a recent update of HA Core broke the dependency.

### Reproduction steps

1. Start HA.
2. Integration fails to load.

### Debug logs

```text
(This is an excerpt, the entire debug log has ~50k lines, I can provide more or even all of it if needed.)


2023-08-18 12:59:55.955 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package async-upnp-client==0.33.2: ERROR: Cannot install async-upnp-client==0.33.2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
2023-08-18 12:59:55.957 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration magentatv: Requirements for magentatv not found: ['async-upnp-client==0.33.2'].
```
```


### Diagnostics dump

_No response_

**Comment by Xyaren** [comment]
Thanks for the report 👍 
I'll look onto it.

**Comment by Xyaren** [comment]
I've release 0.2.0. Could you please check if the problem is solved ?

**Comment by bovender** [comment]
> I've release 0.2.2. Could you please check if the problem is solved ?

Yes, that did indeed fix it! Thanks!!
